name: Report an issue with lspconfig
description: Report an issue with lspconfig
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a question about usage, please use the language servers section on our [discourse forum][https://neovim.discourse.group/c/7-category/7].

        Please note that all language servers have been tested, and if you cannot get *any* language servers to work, it is likely a usage question rather than bug.

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment


  - type: input
    id: neovim-version
    validations:
      required: true
    attributes:
      label: nvim --version

  - type: input
    id: lspconfig-version
    validations:
      required: true
    attributes:
      label: nvim-lspconfig commit hash

  - type: input
    id: language-servers
    validations:
      required: true
    attributes:
      label: What language servers (if problem is isolated to specific servers)?

  - type: input
    id: reproducing-client
    validations:
      required: true
    attributes:
      label: Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.)?

  - type: input
    id: reproducing-servers
    validations:
      required: true
    attributes:
      label: Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.)?

  - type: textarea
    attributes:
      label: How to reproduce the problem from neovim startup
      render: markdown

  - type: textarea
    attributes:
      label: Actual Behavior
      render: markdown

  - type: textarea
    attributes:
      label: Expected Behavior
      render: markdown

  - type: textarea
    attributes:
      label: Minimal init.vim or init.lua and code sample
      render: markdown
      description: You can download a minimal_init.lua from here 
      curl -fLO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua 
      After editing to include your language server, run neovim with nvim -u minimal_init.lua
    

  -type: textarea 
    attributes:
      label: LSP log
      description:
        <!-- If not using the minimal_init.lua please add vim.lsp.set_log_level("debug") to your lua block 
             in init.vim and paste a link to your log file, located at  $HOME/.cache/nvim/lsp.log (formerly $HOME/.local/share/nvim/lsp.log) -->
        <details>
        <summary>Log file</summary>
        <!-- past you log between here -->
        </details>
